spring.application.name=travel
server.port = 2024
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_travel
spring.datasource.username=traveluser
spring.datasource.password=travelpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# JWT Properties
jwt.secret=una_clave_muy_larga_y_segura_de_mas_de_64_caracteres_para_que_funcione_hs512_sin_problemas_1234567890
jwt.expiration.ms=86400000
logging.level.org.springframework=DEBUG
logging.level.com.travel.travel=DEBUG
#logging.level.com.travel.travel=DEBUG
logging.level.org.springframework.security=DEBUG